config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "books#index"
  resources:books,only:[:create,:destroy,:show,:edit,:update] do
    resource:favorites,only:[:create,:destroy]
    resource:comments,only:[:create,:destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to:user
  has_many:favorites,dependent: :destroy
  attachment:image
  has_many:comments,dependent: :destroy
  
  def favorite_by(user)
    favorites.where(user_id:user.id).exists?
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to:book
  belongs_to:user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to:user
  belongs_to:book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many:books,dependent: :destroy
  has_many:favorites,dependent: :destroy
  has_many:comments,dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    books_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action:authenticate_user!
  
  def index
    @book=Book.new
    @books=Book.all
  end
  
  def create
    Book.create(book_params)
    redirect_to root_path
  end
  def destroy
    book=Book.find(params[:id])
    book.destroy
    redirect_to root_path
  end
  
  def show
    @book=Book.find(params[:id])
    @comment=Comment.new
  end
  
  def edit
    @book=Book.find(params[:id])
  end
  
  def update
    book=Book.find(params[:id])
    book.update(book_params)
    redirect_to book_path(book.id)
  end
  
  private
  def book_params
    params.require(:book).permit(:title,:body,:image,:user_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action:find_book
  
  def create
    comment=current_user.comments.new(comment_params)
    comment.book_id=@book.id
    comment.save
    redirect_to book_path(@book.id)
  end
  
  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
  
  def find_book
    @book=Book.find(params[:book_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action:favorite_book
  
  def create
    favorite=current_user.favorites.new(book_id:@book.id)
    favorite.save
  end
  
  def destroy
    favorite=current_user.favorites.find_by(book_id:@book.id)
    favorite.destroy
  end
  
  private
  def favorite_book
    @book=Book.find(params[:book_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/books/edit.html.erb
<div class="w-25 p-5 m-5">
  <h3 class="my-3">編集画面</h3>
  <%= form_with model:@book,url:book_path,local:true,method: :patch do |f| %>
    <%= f.label:title %>
    <%= f.text_field:title,class:"form-control" %>
    <%= f.label:body %>
    <%= f.text_field:body,class:"form-control" %>
    <%= f.label:image %>
    <%= f.attachment_field:image %>
    <%= f.submit "変更",class:"btn btn-primary btn-sm mt-3" %>
  <% end %>
</div>

app/views/books/index.html.erb
<div class="book_top">
  <div class="new_book">
    <%= form_with model:@book,local:true do |f| %>
      <%= f.label:title %>
      <%= f.text_field:title,placeholder:"タイトルを入力",class:"form-control" %>
      <%= f.label:body %>
      <%= f.text_field:body,placeholder:"詳細を入力",class:"form-control" %>
      <%= f.label:image %><br>
      <%= f.attachment_field:image %>
      <%= f.hidden_field:user_id,:value=>current_user.id %>
      <%= f.submit "投稿する",class:"btn btn-primary" %>
    <% end %>
  </div>
  <div class="book_index">
    <% @books.each do |book| %>
      <div class="card" style="width: 200px;">
        <%= attachment_image_tag book,:image,size:"200x250",fallback:"noimage.png",class:"bd-placeholder-img card-img-top w-100" %>
        <div class="card-body">
          <%= link_to book_path(book.id) do %><h5 class="card-text"><%= book.title %></h5><% end %>
          <p class="card-text"><%= book.body %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
<div class="book_top">
  <div class="new_book">
    <div class="card" style="width: 400px;">
      <%= attachment_image_tag @book,:image,size:"400x450",fallback:"noimage.png",class:"bd-placeholder-img card-img-top w-100" %>
      <div class="card-body">
        <h5 class="card-text"><%= @book.title %></h5>
        <p class="card-text"><%= @book.body %></p>
        <span class="fav_btn">
          <%= render "favorites/fav_btn", book:@book %>
        </span>
        <% if @book.user_id==current_user.id %>
          <%= link_to "削除",book_path(@book.id),method: :delete,class:"btn btn-danger btn-sm" %>
          <%= link_to "編集",edit_book_path(@book.id),class:"btn btn-primary btn-sm" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="book_show">
    <div class="comment-index">
      <% if @book.comments.exists? %>
        <% @book.comments.each do |comment| %>
          <div class="comment">
            <%= comment.created_at.strftime("%F") %><br>
            <%= comment.comment %>
          </div>
        <% end %>
      <% else %>
        <p>コメントはまだありません</p>
      <% end %>
    </div>
    <div class="new-comment">
      <%= form_with model:@comment,url:book_comments_path(@book.id),local:true do |f| %>
        <%= f.text_field:comment %>
        <%= f.submit "コメントする" %>
      <% end %>
    </div>
  </div>
</div>

app/views/favorites/_fav_btn.html.erb
<% if book.favorite_by(current_user) %>
  ❤️<%= link_to "お気に入り済み",book_favorites_path(book.id),remote:true,method: :delete %>
<% else %>
  ♡<%= link_to "お気に入り登録",book_favorites_path(book.id),remote:true,method: :post %>
<% end %>

app/views/favorites/create.js.erb
$(".fav_btn").html("<%= j(render "favorites/fav_btn", book:@book) %>");

app/views/favorites/destroy.js.erb
$(".fav_btn").html("<%= j(render "favorites/fav_btn",book:@book) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersPra</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/12120b9d9d.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg shadow-sm navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">BOOKERS</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="#">ホーム画面</a>
              </li>
              <li class="nav-item">
                <p class="nav-link">ログイン</p>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>